### ISSUE TITLE
WebGLEarth is great! Is there any document about functions, events, data, etc?

### ISSUE THREAD

**Issue by eprtha** [webglearth/webglearth2#130]
I have searched a manual to figure out various questions about WebGLEarth but couldn't find one.
If there is a manual, please share.
Even though WebGLEarth development has been stopped about 10 years ago, it seems very useful and powerful and will be much more with manual.

**Comment by sebastian-marinescu** [comment]
Unfortunately the official pages are down, but we can use the internet-archive, to look into the past: [API-Reference](https://web.archive.org/web/20210213164444/http://sites.google.com:80/site/webglearth/api).
These are [all pages ever captured](https://web.archive.org/web/*/https://sites.google.com/site/webglearth/*) in the internet-archive.

In the readme here it says: 

> The supported Leaflet API methods are not yet documented -- the best source of the information are currently the API examples (src/api-l.html, src/api.html, src/polygon.html) and the API symbol exports itselves (src/api.js and src/api-l.js).

You can also find great inspiration on their [examples-page](https://examples.webglearth.com/#apidemo).

And last but not least, you can use the GitHub-Search to search inside the repository, to look up methods, etc.

**Comment by eprtha** [comment]
Thanks for the information.
It helps a lot.
