### ISSUE TITLE
WMS EPSG:900913 or EPSG:3857

### ISSUE THREAD

**Issue by yangxu432** [webglearth/webglearth2#15]
V2 don't have this function for bbox anymore. Is there any ways I can use it?
So I can have a call looks like version 1

(v1)
GET /wms/datasets/CGridTest/?service=WMS&request=GetMap&version=1.3.0&Width=256&Height=256&Layers=u,v&Format=image/jpeg&CRS=EPSG:3857&STYLES=vectors_average_jet_1_1.5_cell_True&BBOX=-10018754.171394622,6261721.357121642,-8766409.899970293,7514065.628545966

current version (v2)
GET /wms/datasets/CGridTest/?service=WMS&version=1.3.0&request=GetMap&styles=vectors_average_jet_1_1.5_cell_True&format=image/jpeg&crs=EPSG:3857&layers=u,v&srs=EPSG:4326&bbox=-90,50.625,-84.375,56.25&width=256&height=256&

**Comment by petrsloup** [comment]
Different tiling scheme has to be used for this to work properly (WebMercatorTilingScheme). I made the required changes, but it will not have any effect until #44 is done.
