### ISSUE TITLE
IE 11?

### ISSUE THREAD

**Issue by MdBee** [webglearth/webglearth2#19]
I'm enjoying working with WebGL Earth.  Thank you for giving the planet this API.  What kind of hoops do we or our users need to jump through in order for it to appear in Internet Explorer?  Hoping for good news.

**Comment by andykay** [comment]
I'm getting issues with Webgleart2 in IE11.0.96 on Windows 8. 

Error: "The browser supports WebGL, but initialization failed"

It looks to me as though getContext('webgl') is returning undefined which could be the problem.

You can see this at http://itopf.dubitcloud.com

Any advice as to what to do? Thanks

**Comment by klokan** [comment]
Do you experience issues also on http://get.webgl.org/?
Do you experience issues also on http://www.webglearth.com/?
Or is it a problem of usage of the API only?

**Comment by andykay** [comment]
On http://get.webgl.org/ I get the "Your browser supports WebGL" message as expected.

On http://www.webglearth.com/ I'm getting the same console error as above.

**Comment by rickturek** [comment]
@klokan 

Any progress on the IE11 issue reported above?

We're still experiencing the issue on http://www.webglearth.com/ 

Any advice? Thanks

**Comment by klokan** [comment]
Anybody here willing to support update of WebGL Earth with donation or at least partly cover the related working time (4-8 hours) required?

**Comment by rickturek** [comment]
What are your costs Petr?

**Comment by klokan** [comment]
Paid 3 hours via https://sites.fastspring.com/klokantech/instant/support will motivate us to do the required work in the first half of the next week. Paid 2 hours within 10 days, paid 1 hour will make this happen in next 20 days. This is to cover the related costs.

As this is an open-source project - anybody can make a pull request and work on the code.
