### ISSUE TITLE
Emitted touch events are not the actual touch events.

### ISSUE THREAD

**Issue by trusktr** [webglearth/webglearth2#32]
WebGLEarth's touch events aren't instances of TouchEvent. They contain a TouchEvent in the `gc` property. 

For example, I've got

```js
    source.on('mousemove', function(event) {
        handler.emit('mousemove', event);
    });
    source.on('touchmove', function(event) {
        handler.emit('touchmove', event);
    });
```

Due to the `handler` implementation, it only works with mousemove, but not with touchmove because `handler` needs to use the `touches` property of TouchEvent. The workaround is

```js
    source.on('touchmove', function(event) {
        handler.emit('touchmove', event.gc); // add .gc
    });
```

It might be better to extend from TouchEvent so that the event can be passed to other handlers that expect TouchEvents. I'm not sure if the indentifier `gc` is a result of minification, but if it is, then a different identifier would need to be used in development.

**Comment by petrsloup** [comment]
You can now access the original browser event in the `event.originalEvent` property.
