### ISSUE TITLE
what is the difference between the wegblearth2 and webglEarth.com?  how can i chose to use?

### ISSUE THREAD

**Issue by lugiser** [webglearth/webglearth2#35]
Excuse me please, I would like to use the webglearth, there are two directories in the github,, which one should i chose? the eabglEarth2 or  webglEarth.com? would you please give me a suggestion, thanks!

**Comment by klokan** [comment]
Repos and descriptions:
`webglearth2` - WebGL Earth 2 - the source code of the project
`www.webglearth.com` - http://www.webglearth.com/ (compiled version of project)
`webglearth2-offline` - Example of offline use of WebGL Earth 2 with tiles rendered by MapTiler
