### ISSUE TITLE
Advanced API demo not working

### ISSUE THREAD

**Issue by veertjetam** [webglearth/webglearth2#39]
The advanced API demo (examples.webglearth.com/#apidemo) is not working in my browsers (chrome, explorer, firefox) on Windows 7, whereas the other demos are working fine (except for the right window of the 2D next to 3D, I am sure it worked a few weeks ago). 

I would like to place buttons to pan to some latitude&longitude, but it is not working if I use the code of the advanced API demo..

**Comment by klokan** [comment]
DNS issue problem. Should be fixed now.

**Comment by klokan** [comment]
BTW Use the new Leaflet API, please.

**Comment by veertjetam** [comment]
Thanks a lot!

2015-02-11 17:43 GMT+01:00 Petr Pridal <notifications@github.com>:
