### ISSUE TITLE
How to change marker dynamically?

### ISSUE THREAD

**Issue by javagc** [webglearth/webglearth2#40]
Hello , I want to Change marker dynamically and add css class for mouseover , Can I achieve it?

**Comment by petrsloup** [comment]
You can create a custom marker (with custom HTML element) and then modify the element:
```
var marker = WebGLEarth.CustomMarker(Math.PI / 4, 0, element); // lat lon in radians !
app.initMarker(marker); // add marker to the app
element.innerHTML = 'my custom text';
element.className = 'my_marker';
```
and you can easily do `.my_marker:hover {...}` in the style definition.
