### ISSUE TITLE
can't remove marker using addTo and removeFrom

### ISSUE THREAD

**Issue by sobbeck** [webglearth/webglearth2#41]
Hi, impossible to remove layer using addTo and removeFrom

**Comment by petrsloup** [comment]
None of the online examples is currently using this, but it is working correctly for me when using `marker.removeFrom(earth)`.

Make sure you are linking the latest script version from ht<span>tp://</span>www.webglearth.com/v2/api.js and that both `marker` and `earth` are defined when executing the code above (or similar).

**Comment by jflee1982** [comment]
how to remove polygon。thank you！
