### ISSUE TITLE
can i insert a picture to the map?

### ISSUE THREAD

**Issue by careyv** [webglearth/webglearth2#43]
I found a interface about Overlays,but could not insert custom image,you u help me?i hope insert custom picture.
thx

**Comment by petrsloup** [comment]
You can pass additional parameters when creating a marker to specify a custom image (and its width and height). For example: `app.initMarker(51.507222, -0.1275, url, width, height)`.

**Comment by klokan** [comment]
@careyv In case you want to create a map from your picture - so it is a new layer in WebGL Earth - then the easiest is to use http://www.maptiler.com/

**Comment by MichaelPoP** [comment]
@klokan 

I would very much like to create a map from an image and apply it to a WebGL Earth instance using the tileLayerJSON method. However it has not been easy for me at all.

I downloaded the free version of maptiler and have converted my image (which has now map info btw, this is a creative usage of this tool) and it has given me an array of files. The most useful is the index.html file which would provide me a preview of my map overlay if I were hosting the file online. 

I keep running into that problem, I have the photo and data and all i want to do is attach it to the map at the set coordinates but it is looking for a url, I would rather just host it locally!

Can you help me with this?

**Comment by klokan** [comment]
Textures and images for WebGL must be available via http:// protocol - so either you host the images somewhere online or you must start a webserver locally  (such as with command `python -m SimpleHTTPServer` and access your files via http://localhost:8000/).

- If you want to use your image as a custom map overlay / globe here is a tutorial step-by-step:
https://www.youtube.com/watch?v=pf8itiTwo6w&index=13&list=PLGHe6Moaz52PiQd1mO-S9QrCjqSn1v-ay
- If you want to use your image as a marker at given lat/lon position - above is a line of code doing this.
- If you want a private support, contact info@klokantech.com and purchase one hour of support: http://www.maptiler.com/support/one-to-one/
