### ISSUE TITLE
use image as map?

### ISSUE THREAD

**Issue by Orbyt** [webglearth/webglearth2#46]
Im trying out the basic examples on the demo page, but is there a way to replace the basic earth image/layer with a custom image to wrap the globe?

**Comment by klokan** [comment]
Yes of course it is.

See this video tutorial:
https://www.youtube.com/watch?v=pf8itiTwo6w&list=PLGHe6Moaz52PiQd1mO-S9QrCjqSn1v-ay&index=13

You need to prepare the tiles for from your image which could be easily done with the MapTiler (http://www.maptiler.com/) software - developed by the same team as WebGL Earth.
