### ISSUE TITLE
the 'hello world' example has outdated API URL

### ISSUE THREAD

**Issue by MichaelPoP** [webglearth/webglearth2#48]
![screen shot 2015-05-30 at 8 36 13 pm](https://cloud.githubusercontent.com/assets/8924827/7900427/8edea86e-070b-11e5-9fa7-4ad872d07a84.png)

This is a minor thing but I am new to programming and little things like this make it hard to get started.

all that needs to be done is to change the the URL from
`<script src="http://www.webglearth.com/api.js"></script>`
to
`<script src="http://www.webglearth.com/v2/api.js"></script>`
so just add v2, which is stated just below the code but if you are lazy like me and copy and paste the code it will not work. thanks!

**Comment by klokan** [comment]
Done. Thanks for the report.
