### ISSUE TITLE
Touch event dont alert latitude

### ISSUE THREAD

**Issue by sarahansen223h** [webglearth/webglearth2#50]
- Let say i want to click on the globe and the browser most alert me back the latitude of the place that i have clicked. What i did was this:

earth.on('click', fire);

var fire = function(e) {

alert('You clicked at ' +e.latitude);
};
it worked on the web browser and retuned the latitude, but it did not work on the mobile( iPhone ) browser.

so what i did next was this instead:

 earth.on('touchstart', fire);

 var fire = function(e) {

    alert('You clicked at ' +e.latitude);
    };
it works on the mobile browser (iPhone), but the problem it dont return latitude. Instead it alert me with "NULL". I want it to return the latitude when i touch the globe in the mobile browser.

Please fix it

**Comment by klokan** [comment]
This is open-source project - feel free to fix the source code and provide a patch.
Or do you prefer to support the development time we need to fix it and release update?
Estimate @klokantech is 1-2 hours: purchased at http://www.maptiler.com/support/one-to-one/

**Comment by sarahansen223h** [comment]
How much do i need to pay for a fix?

**Comment by klokan** [comment]
2 hours.

**Comment by klokan** [comment]
The work is supported by Miizee.com (to be mentioned in the source code as well)

**Comment by philipjmurphy** [comment]
FYI - this is fixed for the 'touchstart' event, but not the 'touchstart' event. As a work-around just save the event.latlng property in the 'touchstart' event and reuse in the 'touchend' event.

**Comment by eprtha** [comment]
> FYI - a 'touchend' event does not receive the latlng property populated. As a work-around just save the event.latlng property in a 'touchstart' event and reuse in the 'touchend' event.

Would you share some sample codes? I'm having hard time to get the lat,lng data from the 'touchstart' event...
