### ISSUE TITLE
Polygon onClick Event not triggered in the entire surface

### ISSUE THREAD

**Issue by benfaidao** [webglearth/webglearth2#57]
Hello,

I am building a web app that will use WebGL Earth, I wanted to draw polygons that represents areas in some cities.

I used API methods for drawing polygons, apparently it works correctly.

In addition of this, I wanted to add an event onClick for each polygon, the event onClick is triggered when clicking in the entire surface of area for simple polygons, but for other polygons, the event is launched in a part of polygon but not in the whole area surface.

For information, I am linking the latest script version from http://www.webglearth.com/v2/api.js .

![polygons webglearth](https://cloud.githubusercontent.com/assets/13163999/8499830/e8c2d8e6-2196-11e5-93cc-edb9770a0a4e.jpg)

Please let me know your thoughts on this. Thanks!
Oussama

Code of the second polygon: 

var showInfo = function() {
   alert('Hello world!');
}

var poly2 = new WebGLEarth.Polygon(earth);
coordinates = [[48.1239683736923,-1.66584766415147],[48.1237797235126,-1.66557988111915],[48.1233350483757,-1.66495569444435],[48.1230757284176,-1.66457788140545],[48.1227177151745,-1.66407406004392],[48.1223700619834,-1.66356579986888],[48.1217879555263,-1.66272627790082],[48.1217652871103,-1.66270846356172],[48.1212838335046,-1.66233011894021],[48.1202850937404,-1.66154554710104],[48.1193856698268,-1.6608337698992],[48.1192709919708,-1.66074252175633],[48.1187848441461,-1.66035570251008],[48.1182425352473,-1.65993447402531],[48.1176896656272,-1.65950032387194],[48.1171033592678,-1.65902629142436],[48.1166209977395,-1.65865101051243],[48.1161716174912,-1.65830011152583],[48.1159260699719,-1.65810422559441],[48.1154827359352,-1.65774855249912],[48.1148550465413,-1.65724498812588],[48.1145924209122,-1.6570343013129],[48.1138755902965,-1.65677714861834],[48.1133461592916,-1.65658724871806],[48.1130238989449,-1.65648167335475],[48.111833969176,-1.65609185327414],[48.1116936951302,-1.65604460868271],[48.110906306854,-1.65578713522964],[48.1103454295206,-1.65560373495034],[48.1103022316127,-1.6555896096362],[48.1101046908642,-1.65552715955554],[48.1099326249421,-1.6554727628318],[48.1099459419857,-1.65533916196322],[48.1099890020886,-1.65441945019569],[48.1100335327909,-1.65376893561039],[48.1100661867474,-1.65336542235252],[48.1100499371294,-1.65332207228086],[48.1099046249551,-1.65293442096201],[48.1096725421505,-1.6523152956918],[48.1096220055726,-1.65211522329478],[48.1097568185366,-1.65105481059695],[48.1102203223382,-1.64989768938352],[48.1103165809066,-1.64957064375285],[48.1104029086184,-1.64911796474352],[48.1104726215568,-1.64869885457508],[48.1105126616673,-1.64848351539097],[48.1106683745134,-1.64772475369696],[48.1108864332444,-1.64702975553427],[48.1109554914543,-1.64687342758706],[48.1110097393828,-1.64671536916393],[48.1112567514248,-1.64599566351654],[48.1114564799619,-1.64510059464416],[48.1118657310675,-1.64326641702346],[48.1119710109871,-1.64279458892782],[48.1120571373836,-1.64240856558441],[48.1121164340159,-1.64214279019886],[48.112224658049,-1.64165770881375],[48.1122680180178,-1.64116800539175],[48.1123371076403,-1.64030719241906],[48.1123530303713,-1.63981020715584],[48.1123671887458,-1.63925955007864],[48.1123612555969,-1.63895692348119],[48.1123606683164,-1.63830401741626],[48.1123066310166,-1.63743614190837],[48.1121755933737,-1.63668939006632],[48.1119436139819,-1.63510549847759],[48.1119413324874,-1.63510424797381],[48.1118568036895,-1.63502628190873],[48.1116274878204,-1.63473792235237],[48.1114831626086,-1.63453618230276],[48.1112537580913,-1.63419857534833],[48.111136756201,-1.634052170044],[48.1109132987587,-1.63374806552378],[48.1106574372752,-1.63331565699149],[48.1105782049537,-1.63339020655565],[48.1105164797972,-1.63344843454692],[48.1104563003868,-1.63355550613069],[48.1104004401469,-1.6335934065015],[48.1100874253137,-1.63383692400309],[48.1098361367753,-1.63395063582256],[48.1096820782286,-1.63397473344833],[48.1095028730761,-1.63397665921229],[48.1093582848958,-1.63398263730914],[48.1090594975378,-1.63398713732653],[48.1089757641556,-1.63396319950799],[48.1089085310804,-1.63395016218589],[48.1088116284157,-1.63392880828582],[48.1087624180906,-1.63391348882778],[48.1087124437667,-1.63389029747369],[48.1086642001917,-1.63386887614777],[48.1086233156553,-1.63385713020601],[48.1085668494037,-1.63384075529399],[48.1084919791848,-1.63381599985176],[48.1084796153947,-1.63388579081355],[48.1083964100087,-1.63389123025248],[48.1083544876848,-1.63389405578397],[48.1083147362717,-1.63389667275915],[48.1082726397911,-1.63389934809513],[48.1080848162477,-1.63391166631023],[48.1080681044261,-1.63391272091875],[48.1079781187427,-1.63391871748139],[48.1079432514442,-1.63392087590703],[48.1078892230514,-1.63392449714529],[48.1078523607795,-1.63392697006025],[48.1078522668147,-1.63392697641637],[48.1077401867412,-1.63435555609574],[48.1075999457955,-1.63485503057853],[48.1075340240731,-1.63507649809312],[48.1075335124099,-1.6350782158787],[48.1072988898093,-1.63586642644395],[48.1071035210414,-1.63657864634169],[48.1069831429382,-1.63701747651495],[48.1069308302345,-1.63722454718638],[48.1068675706042,-1.6374749489063],[48.1068071077282,-1.63776286632709],[48.1068070686273,-1.63776305385024],[48.1067815378929,-1.63788462538021],[48.106704142756,-1.63827491879793],[48.1067033056126,-1.63827914188622],[48.1066691409098,-1.6384514241132],[48.1065995225519,-1.63883673680413],[48.1065165790958,-1.63935714644116],[48.1065005945926,-1.63948636534927],[48.1064706070303,-1.63972878197876],[48.1064197652136,-1.64018985961471],[48.1063934515162,-1.64044276884328],[48.1063934218742,-1.64044305676944],[48.1063732360977,-1.64063706532379],[48.1063529395335,-1.64084682442689],[48.1063214410918,-1.64117233320031],[48.1062962495177,-1.64144165215513],[48.1062895567473,-1.64151489944235],[48.1062687086742,-1.64174307715692],[48.1062456453483,-1.64204101824114],[48.1062322404845,-1.64231231503572],[48.1062321954913,-1.64231322850549],[48.106225663346,-1.64244543468418],[48.1062119134899,-1.64272373371873],[48.1062101127874,-1.6429847606977],[48.1062070036652,-1.64343528175157],[48.106208907801,-1.64376583447527],[48.1062117906823,-1.64395484093375],[48.1062125756673,-1.64400627797203],[48.1062125774036,-1.64400639113679],[48.1062129614198,-1.64403159430225],[48.1062129709313,-1.644032228813],[48.1062162625252,-1.64424804572624],[48.1062285385355,-1.64452621701931],[48.1062382601107,-1.6447465146826],[48.1062647549829,-1.64518433372861],[48.1062647603405,-1.64518446874521],[48.1062736906693,-1.64539378884932],[48.1062737185934,-1.64539443578294],[48.1062802072468,-1.64554652048026],[48.1062869031712,-1.64565895111925],[48.106292676262,-1.6457558850839],[48.1063054124594,-1.64596975522818],[48.1063110455535,-1.64613447523015],[48.1063207872701,-1.64641934809032],[48.1063261403961,-1.64655310011705],[48.1063262084373,-1.64655480541645],[48.1063346918554,-1.64676680625059],[48.106344057612,-1.64720350277097],[48.1063398919596,-1.64769854266618],[48.1063163613502,-1.64826670851604],[48.1062982595397,-1.64847496698047],[48.1062982276862,-1.64847533138863],[48.1062824187299,-1.64865720297948],[48.1062202072882,-1.64914604418473],[48.1061903536522,-1.64936810602407],[48.1061903215045,-1.64936834394246],[48.1061620023037,-1.6495789887509],[48.1060905499777,-1.64990308252605],[48.1060174799324,-1.65023451240168],[48.1059742564885,-1.65037193483972],[48.1059295365018,-1.65051137734753],[48.1058855699505,-1.65064555465536],[48.1058855010694,-1.6506457650432],[48.1058716011074,-1.65068818393006],[48.1058715579241,-1.65068831591496],[48.1058705528373,-1.65069652331529],[48.1058704975927,-1.65069697574785],[48.105864125287,-1.65074898896762],[48.1058332306899,-1.6508832846174],[48.1058008466899,-1.65102405677936],[48.1055281797828,-1.65215730534793],[48.1055137745197,-1.65221874400111],[48.1054506910453,-1.65248780841582],[48.1054233553271,-1.65260667344738],[48.1053610772175,-1.65287747785975],[48.1053206154712,-1.65309810790415],[48.1053205645763,-1.65309838583047],[48.1053036087674,-1.65319083771095],[48.1052992881751,-1.65321677454127],[48.1052717088581,-1.65330933603424],[48.1051370228735,-1.65432985200012],[48.1051213767697,-1.65444913143016],[48.1051213468412,-1.65444935877904],[48.1051106324358,-1.65453103891024],[48.1047810338325,-1.65712083758028],[48.1047318357879,-1.65754692772993],[48.1047273454819,-1.6575853251106],[48.1047150281557,-1.65769065666212],[48.1047028681315,-1.65782815536746],[48.1047028401075,-1.65782846898524],[48.1046992467812,-1.65786909983817],[48.1046806697871,-1.65805880228456],[48.1046764923864,-1.65815007444398],[48.104667931894,-1.65833713386455],[48.1046606734114,-1.65853668369882],[48.1046276064232,-1.65952370847328],[48.1046145280935,-1.65985596947925],[48.1045997252228,-1.6600927282011],[48.1045783646173,-1.66042096210088],[48.1045610507119,-1.6606545743579],[48.1045610386959,-1.66065473740018],[48.1045474639896,-1.66083788980278],[48.1045074917315,-1.66109419978264],[48.1044953511691,-1.66117204411099],[48.104495322123,-1.66117222713893],[48.1044878958372,-1.66121984727307],[48.1044491162558,-1.66145009824423],[48.1043551118606,-1.66234747494396],[48.1042572430238,-1.66313310680038],[48.1042690482209,-1.66314511689011],[48.1042909797803,-1.66316743011829],[48.104282985248,-1.66324019071347],[48.1042447616005,-1.66358764867788],[48.104221817381,-1.66375711812768],[48.1042217927653,-1.66375730289941],[48.104231171619,-1.66377601398488],[48.1042437915914,-1.66380118908863],[48.1043009327831,-1.6638926107104],[48.1043008868925,-1.66389278683194],[48.1042247279036,-1.6641883465071],[48.1042245866669,-1.66418889607301],[48.104200912541,-1.66428076651648],[48.1041040220895,-1.66475953047885],[48.1041037246001,-1.6647609995515],[48.1040161246566,-1.66519384624655],[48.1039765787767,-1.66543742812479],[48.1039147546795,-1.66584734397066],[48.1039033648403,-1.66592894465597],[48.1039031095884,-1.66593077135293],[48.1038685689281,-1.66617822620898],[48.1037763725711,-1.66679984381317],[48.1037329633731,-1.6670925150915],[48.1036931849407,-1.66739066296637],[48.1036467415261,-1.66773876484062],[48.1035489338089,-1.6684261054154],[48.1035434993112,-1.66846429744786],[48.1034819852682,-1.66889656983397],[48.103210397878,-1.6710342662039],[48.1029849753492,-1.67280833648411],[48.1029842188719,-1.67281428944045],[48.1029735034514,-1.67289861502286],[48.1029734968923,-1.67289866554936],[48.1029454343463,-1.67311306078512],[48.1029446372285,-1.67311914861587],[48.1027765778352,-1.6744030341987],[48.1027446707557,-1.67471062097077],[48.1027113923012,-1.67505002679874],[48.1027041586953,-1.67519566355204],[48.1026839256394,-1.67577048488972],[48.1026676215192,-1.67618932191379],[48.1026461452241,-1.67663798015082],[48.1026461385543,-1.67663803335724],[48.1026455039528,-1.67664297891062],[48.1028528883903,-1.67671037907144],[48.1028639210094,-1.6767142368467],[48.1028913572186,-1.67660234842013],[48.1029452881547,-1.67638241411501],[48.1030054155164,-1.67620235052043],[48.1030692209425,-1.67605369619548],[48.1031204263557,-1.67595340591835],[48.1031815565011,-1.67584836499148],[48.1037315716547,-1.67501086525406],[48.1037419527392,-1.67492702098863],[48.1039300082976,-1.67340802225625],[48.104250841075,-1.67351447684669],[48.1042542645264,-1.67349276958722],[48.1043969869018,-1.67258773850454],[48.1044018913148,-1.67255663640047],[48.1046986547449,-1.67262661079364],[48.1049434075931,-1.67269473933742],[48.1057687598986,-1.67292448609738],[48.1058064648607,-1.67293478259989],[48.1070274555562,-1.67326820053315],[48.1070815531292,-1.67328389806968],[48.10748557346,-1.67340113786173],[48.1078579011431,-1.67349434948746],[48.1078579572664,-1.67349436533675],[48.1087786624563,-1.67375315631397],[48.1087787480968,-1.67375317752974],[48.1087912969564,-1.67375637871542],[48.1093789275999,-1.67391761746383],[48.1098634584754,-1.67404728819034],[48.1098647385101,-1.67404763024599],[48.109869348724,-1.67404886345041],[48.1098694529995,-1.67404889173798],[48.1099268313064,-1.67406955440222],[48.1101786368674,-1.67413336854617],[48.110202746463,-1.67413898610784],[48.1104251955697,-1.67419081857602],[48.1106541946153,-1.67424417895691],[48.1106542937221,-1.67424420139488],[48.1106657213704,-1.67424678855929],[48.1106578478194,-1.67433832947816],[48.1109121828876,-1.67449301022253],[48.1113718200351,-1.67477255644673],[48.1119485883326,-1.67511184229272],[48.1124085646878,-1.67514560576735],[48.1126322929563,-1.67527433992303],[48.1128472263574,-1.67532019960413],[48.1130538331136,-1.67528053509605],[48.1131926994645,-1.67523593956354],[48.1133044386707,-1.67518988945229],[48.1134108094193,-1.67514605160924],[48.1135230692196,-1.67509985051386],[48.1135968537811,-1.67507801412278],[48.1145573936723,-1.67447521804049],[48.1146729843323,-1.67445124956597],[48.1148001128241,-1.67442496293158],[48.1151034665271,-1.67437710910558],[48.1153887172088,-1.67431751754816],[48.1160535142577,-1.67417863434341],[48.1163593428049,-1.67414082539876],[48.1164498109255,-1.67413637732437],[48.1165531532521,-1.67433171267243],[48.1169127859624,-1.67526456251322],[48.1169876104303,-1.67545865372932],[48.1170280075081,-1.67563523323917],[48.1172310851353,-1.67753245842811],[48.1172344938545,-1.67755523211846],[48.1172593080535,-1.67772100664725],[48.1172627564842,-1.67774404368127],[48.1172649798016,-1.67774051251751],[48.1172670961596,-1.6777371519687],[48.1173778702631,-1.67756124952367],[48.1182300669362,-1.67632369034509],[48.1182823038245,-1.67641737789394],[48.1183897198542,-1.67652131853691],[48.1184624515687,-1.67653424002453],[48.118850407212,-1.67733742010425],[48.1191546906932,-1.6783056757935],[48.1196764209129,-1.6799664068331],[48.1197754303319,-1.68023256276423],[48.1200061791107,-1.6807311106348],[48.1202855890345,-1.68123411630669],[48.1203119712116,-1.68119428084222],[48.1204644469208,-1.68096404896201],[48.1205119786802,-1.68089227700234],[48.1205121457502,-1.68089202436609],[48.1206842035911,-1.68063222050676],[48.1207742185845,-1.68048888042372],[48.1209044902945,-1.68024717765645],[48.1210043249984,-1.68004703489988],[48.1210044103058,-1.68004686500292],[48.1210602731653,-1.6799348719312],[48.1211001426463,-1.67985494453088],[48.1211206887536,-1.67979064497037],[48.1211510442738,-1.67969564523771],[48.1211706866872,-1.6796341757716],[48.1212130053372,-1.67950173641735],[48.1212377588464,-1.67941771539281],[48.1212443589319,-1.67939531122169],[48.1212639302187,-1.67929031969044],[48.1212669032561,-1.67924916275008],[48.1212702993215,-1.67920214839038],[48.1212671003244,-1.67912858235779],[48.1212670936476,-1.67912843640887],[48.1212662689356,-1.67910948448025],[48.1212594382465,-1.67907153835842],[48.1212522211345,-1.67903144028688],[48.1212330926256,-1.67899207533172],[48.1212330152983,-1.67899191624239],[48.1212154631856,-1.67895579636923],[48.1211948660215,-1.67891115736639],[48.1211947724301,-1.67891095508268],[48.1211666904066,-1.67885009462976],[48.1211259023287,-1.67872491508922],[48.1211130716883,-1.67867207478689],[48.1211067174563,-1.6786309853184],[48.1210919613721,-1.67853556940326],[48.1210845715313,-1.67842579923171],[48.1210837574063,-1.67827532165065],[48.1211054351018,-1.67812756047046],[48.1211403069824,-1.67793141976229],[48.1211675198121,-1.67773469293611],[48.1211680302291,-1.67767050460728],[48.1211680325112,-1.67767024911935],[48.1211690695873,-1.67753983107242],[48.1211145682928,-1.67666399579532],[48.121126932455,-1.67652252179537],[48.12112709587,-1.67652065255215],[48.1211809617903,-1.67590430899706],[48.1212060979666,-1.67529994055859],[48.1212493289367,-1.67403590631207],[48.1212969198421,-1.67361581829212],[48.1213231505332,-1.67346136889491],[48.1213449212507,-1.67333318274676],[48.1213971643931,-1.67300124557185],[48.121439989596,-1.67264568660774],[48.121472846672,-1.6725069525771],[48.1214996227441,-1.67235944601132],[48.1214997134155,-1.67235894418282],[48.1215610128607,-1.67202124379265],[48.1215953011577,-1.67184062659808],[48.1216281732265,-1.6717538034383],[48.1216282468789,-1.67175360959254],[48.1216402523047,-1.67172189968616],[48.121673474392,-1.67166481059434],[48.1217169820595,-1.67159004408002],[48.1217458847278,-1.67154037700104],[48.1217678739489,-1.67150258837593],[48.121943202372,-1.67123346860276],[48.1219714965717,-1.67120982581534],[48.121992282311,-1.67119245770119],[48.1220959649476,-1.6710659950345],[48.1221337988576,-1.67101279768054],[48.1221339345634,-1.6710126067623],[48.1222285508162,-1.67087956744886],[48.1223117623528,-1.67072346932871],[48.1223659837217,-1.67061706868977],[48.1223662461042,-1.67061655414458],[48.1223894800137,-1.67057096153335],[48.1225142338908,-1.67037791957059],[48.1226624114503,-1.67020671440128],[48.1227163774987,-1.67017633091616],[48.1227165020183,-1.67017626010209],[48.1227377086845,-1.67016432072507],[48.1228163415032,-1.67014223436769],[48.122851269012,-1.67014069464957],[48.1228512988016,-1.67014069331064],[48.1228662526273,-1.67014003456176],[48.1228663537214,-1.67014003026118],[48.1228547915027,-1.67008612395257],[48.1228547839951,-1.67008608693592],[48.122836762879,-1.67000206877207],[48.1228041982293,-1.66988028778224],[48.1228041807652,-1.66988022967691],[48.1228028664426,-1.66987580542061],[48.1227704371182,-1.66976664428479],[48.1227098523336,-1.66956719807604],[48.1227097259759,-1.66956678154723],[48.1226680983063,-1.6694297453557],[48.1226474058146,-1.66938943001522],[48.1225917687047,-1.66928103290678],[48.1225968636021,-1.66927523370844],[48.122951439348,-1.66893550166061],[48.1231843314486,-1.66875431773282],[48.1238221799445,-1.66828855491858],[48.1239926376538,-1.66814706630907],[48.1240733368648,-1.66807025903986],[48.1241496370593,-1.66798417074705],[48.1245376882259,-1.66752107632001],[48.1248606492881,-1.66711426089558],[48.1239683736923,-1.66584766415147], [48.1239683736923,-1.66574766415147]];
		
poly2.addPoints(coordinates);
poly2.showDraggers(false);
poly2.onClick(showInfo);

**Comment by benfaidao** [comment]
There is a troubleshooting solution for this bug.

We can attach an event handler to the specified element click of the earth:
earth.on('click', onClickEvent);

When we click on a point of the globe, the method onClickEvent is triggered.
We define the method onClickEvent, it will have a parameter that recovers the longitude and latitude of the point when clicking, so we check in the polygons coordinates if this point exists in surface of a polygon.

For testing if a point is in a polygon, we can use this solution : https://github.com/substack/point-in-polygon

Thanks!
Oussama

**Comment by petrsloup** [comment]
WebGL Earth is optimized for smaller polygons (which are actually triangulated for rendering and computational purposes).

The polygon you are trying to display has unnecessarily large number of vertices in some parts. This is causing some floating point precision issues in the implemented algorithm.

If you take for example every fifth element of the coordinates array, the detection works ok (and the polygon looks virtually the same): http://jsfiddle.net/8twrncez/

I suggest you either:
a) Preprocess your data to contain more manageable number of vertices.
b) Use some other algorithm for testing if a point is in the polygon (as you described above), but it will have larger computational overhead, because it won't be able to reuse the values that are precomputed during the polygon initialization.

**Comment by benfaidao** [comment]
Thank you for your reply.

For the moment, I opted to use some  https://github.com/substack/point-in-polygon algorithm for testing if a point is in the polygon.
I will incorporate later a code to reduce the number of vertices and optimize execution time and memory usage.

It can be interesting for WebGL Earth project and for other developers to incorporate data preprocessing for removing unnecessary vertices, of course after the most important points to add to this interesting project.

Thank you!
