### ISSUE TITLE
removeFrom doesn't work on layers

### ISSUE THREAD

**Issue by JanWerder** [webglearth/webglearth2#58]
WE.tileLayer(mapURL).removeFrom(earth);

where earth is my map and mapURL a string url, that has previously been added to the map.
Throws: Uncaught TypeError: Cannot read property 'e' of null

**Comment by petrsloup** [comment]
By calling `WE.tileLayer(mapURL)` you *always* create a new layer and it is not initially added to the `earth`, therefore calling `removeFrom` fails.

You need to keep the instance of the layer that was returned:
```
var layer = WE.tileLayer(mapURL);
layer.addTo(earth);
...
layer.removeFrom(earth);
```
