### ISSUE TITLE
Using toDataURL() to capture WebGL Earth as an image?

### ISSUE THREAD

**Issue by georgemandis** [webglearth/webglearth2#60]
I'm trying use the canvas method `.toDataUrl()` to capture a PNG of the current WebGL instance. Here's an example of what I've tried:

- I've copied the code from [this basic example page](http://examples.webglearth.com/examples/satellite.html) verbatim.
- That runs fine and as expected.
- I've exposed the `earth` variable globally at the top of my example so I can access it in the console. So the JavaScript portion of that page, on my version, looks like this:

      var earth;
      function initialize() {
        var options = {atmosphere: true, center: [0, 0], zoom: 0};
        earth = new WE.map('earth_div', options);
        WE.tileLayer('http://otile{s}.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.jpg', {
          subdomains: '1234',
          attribution: 'Tiles Courtesy of MapQuest'
        }).addTo(earth);
      }

- Still works and looks fine, as you'd expect.
- In the console I can now interact with the `earth` variable and tried: 1earth.toDataUrl()`. I get a correctly formatted data uri but it's for an empty PNG image. The dimensions of that empty image are correct, but it's empty.

I thought that maybe "preserveDrawingBuffer" needed to be set to true when the context was retrieved somewhere in the API, but I think it's doing that? Maybe it's not loading the "experimental-webgl" context?

To reiterate my question in a nutshell: I want to save the current state of the WebGL Earth as a PNG and reasoned .toDataUrl() was the way to go. Any thoughts on how this can be done?

I need to familiarize myself with the non-compressed version of this code, but this seems like an issue others might've had so I wanted to post here first.

**Comment by petrsloup** [comment]
The problem is that the `toDataUrl` has to be called just after the rendering is finished.

There are methods in the API to do this (see https://github.com/webglearth/webglearth2/blob/master/src/api.js#L391):
`earth.saveScreenshot(name)` shows file save dialog if the browser supports it
`earth.getScreenshot(function(dataUrl) {...})` passes dataurl string to the callback function

**Comment by georgemandis** [comment]
Can't believe I missed that... thanks!
