### ISSUE TITLE
Type of convertion on the latitude and longitude 

### ISSUE THREAD

**Issue by amgadfahmi** [webglearth/webglearth2#61]
Hi,

Am storing all the markers coordinates in a private array in order to remove them later from the map at certain point. But I realized that the coordinates on the map are different (R,P) parameters, can you please refer which one belongs to whom and also what is the conversion for this to get the same value, for example the following latitude 25.95230175 what will be the value after the conversion and what is the equation.

**Comment by petrsloup** [comment]
There is no special conversion, the degree values are only converted to radians for optimization reasons.
You can simply use `x * Math.PI / 180` to convert to radians and `x * 180 / Math.PI` to convert back.

**Comment by amgadfahmi** [comment]
Thanks @petrsloup
