### ISSUE TITLE
Safari iOS9 broken

### ISSUE THREAD

**Issue by klokan** [webglearth/webglearth2#64]
I apologize if you are already aware of this, but there appears to be an error that was introduced in iOS 9’s version of safari. It is causing the entire globe texture and tile layer to not render leaving the globe blank. I have found a couple other WebGL based API’s that have run into this same error and found the changes they did to work around this error.
https://github.com/NASAWorldWind/WebWorldWind/commit/ce5d1f2560abf1e3e9e0fbcc14338013c8938c29?diff=split
https://github.com/xml3d/xml3d.js/commit/00f8f3018cf37ecb7bc7ddd265b21d1000bc4ebb?diff=split
 
In the 1.14 version of Cesium they also mentioned in their changelog that they have created a fix for this by “hard-coding constants instead of accessing them through ‘WebGLRenderingContext.’”
http://cesiumjs.org/2015/10/01/Cesium-version-1.14-released/
 
I do not have the background or full knowledge of how to fix this error myself so I am hoping that this helps you and your team in creating a fix instead.
I am very impressed and thankful for all the work you’ve done and hope to see this issue resolved soon.

Thank you again,
Mitchell Adams.

**Comment by petrsloup** [comment]
@klokan Can you please confirm this is fixed now? It seems to be working okay on iPad with iOS 9.0.2.

**Comment by Virusbomb** [comment]
Yes this issue is now fixed from what I can tell, thank you.

**Comment by klokan** [comment]
Tested. Thanks @petrsloup
