### ISSUE TITLE
Tiles not showing

### ISSUE THREAD

**Issue by gregora** [webglearth/webglearth2#65]
Hi!

We are using your plugin in our application which works fine while testing on a local machine. When we package the application in a war and deploy it in a web server (Grails/Tomcat), we notice the tiles are not showing. 

It is not a CORS or similar problem, since we tried loading tiles offline and in both cases we see they are getting fetched from the web server succesfully. They are just not showing on the globe which remains blue all the time.

I understand I probably didn't give you enough info, but I would like to check if you experienced something similar before.

Empty globe:
![empty globe](https://cloud.githubusercontent.com/assets/4229278/11112554/999e3aa4-8914-11e5-9fea-290fc9d353a1.png)

Tiles actually loaded from server:
![tiles loaded](https://cloud.githubusercontent.com/assets/4229278/11112573/df103650-8914-11e5-9d63-7a0970938c6e.png)

It would be awesome If you could give me a tip on how to solve/debug this.

Thank you,
Gregor

**Comment by petrsloup** [comment]
Hi! I'm afraid we haven't experienced this before. Are there any errors/warnings in the console? Without it, it would be very hard to track this down..

**Comment by gregora** [comment]
Thanks for a quick reply!

No warnings in the console unfortunately. Is it possible to turn on debug logging or something?

**Comment by petrsloup** [comment]
No, there is no additional logging to be enabled..

Is http://www.webglearth.com/ and http://examples.webglearth.com/ running ok?

**Comment by gregora** [comment]
Yup, both are showing.

**Comment by klokan** [comment]
I guess this is CORS related.

Host the textures on the same server or ensure the server provides CORS.

WebGL security restrictions in a webbrowser does not display tiles if they are tainted.
