### ISSUE TITLE
To minimize or to not minimize

### ISSUE THREAD

**Issue by luxigo** [webglearth/webglearth2#69]
webglearth2 and cesium are great :+1: 

But it would be nice to add some support (script/doc) to run an unminimized build of webglearth2  and cesium (with plovr ?)

I like what makes Javascript so flexible. Thus I don't like private declarations, obfuscated code and 4th generation languages compiling into Javascript...

It is so useful to be able (at runtime) to observe methods, replace/add prototype methods or to add hooks to prototype methods (eg for mousewheel events) and just having to reload the page.

Thanks in advance :-)

**Comment by klokan** [comment]
This is possible with the debug mode already.

Please read this ticket: 
https://github.com/webglearth/webglearth2/issues/78
