### ISSUE TITLE
Infinite tile looping

### ISSUE THREAD

**Issue by JanTerlecki** [webglearth/webglearth2#70]
Hi,

I'm working with some legacy code using WebGLEarth and I'm stuck with a bug causing the browser to infinitely loop for a missing tile.

     WE.tileLayer('http://otile{s}.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.jpg', {
                    subdomains: '1234',
                    attribution: 'Title'
                }).addTo(earth);

I'm using this JavaScript code to map tiles onto the globe. My browser often loops, this is from Chrome developer tools:

![image](https://cloud.githubusercontent.com/assets/13135682/12976893/73d658b0-d0c7-11e5-8f0f-acd1b77eb9ea.png)

Have anyone got any idea what might be causing this? Thank you in advance for any help

**Comment by petrsloup** [comment]
@JanTerlecki Hi, this seems to be working fine for me: https://jsfiddle.net/L4sc7006/

Can you please provide more details (exact code) where the issue happens?
Or even better fork the fiddle above and modify to show the issue?

**Comment by JanTerlecki** [comment]
Thanks for quick reply,

I've discovered that this issue only happens after other javascript action on my app, I've put it on a staging server for now if you'd like to see:

52.36.6.144

The issue only happens when you search for someone in the search bar (eg. Joseph Stalin), perhaps it has something to do with async http requests or other frameworks (DevExpress, Knockout, Jquery) that are somehow messing with WebGL. I'm quite not sure, this is legacy code and not very decent to be honest. Thanks for your time.

**Comment by petrsloup** [comment]
@JanTerlecki I'm still not able to reproduce the problem (Chromium 48). However it seems like some of your frameworks might be modifying prototypes of some objects and thus changing the standard behavior.

I'm afraid there's nothing we can do about this in this case. If you manage to create a minimal example of the bug (ideally only with WebGL Earth and *pure* javascript) let us know.
