### ISSUE TITLE
polygon.removeFrom is not a function

### ISSUE THREAD

**Issue by patrickmatte** [webglearth/webglearth2#73]
How do I remove a polygon from the globe?

`				var polygon = WE.polygon(path, options);
				polygon.addTo(this.earth);
`
I tried to call removeFrom() and destroy() but both of these are not methods of the polygon object.

**Comment by vmikeska** [comment]
polygon.destroy(); Works for me.

**Comment by petrsloup** [comment]
`polygon.destroy()` is the right way to destroy the polygon
