### ISSUE TITLE
setCenter animation, allow user to specify direction

### ISSUE THREAD

**Issue by mayur07** [webglearth/webglearth2#76]
I was trying to rotate earth horizontally using `setCenter`, and it works. I used the option 

`dragging:false`

and rotated it lwith following code.

```
earth.setCenter([earth.getCenter()[0], e.longitude]);
```
This rotates the earth horizontally, but the only problem is I don't find any way to rotate it specified direction.

For example I was wondering if something was there like `setCenter(latLon,direction)`.

**Comment by klokan** [comment]
See: http://examples.webglearth.com/#animation

The setCenter is a new absolute position. By setting the new positions in regular intervals you can define the rotation direction, speed, path on which it rotates, etc.
