### ISSUE TITLE
MapQuest API changes

### ISSUE THREAD

**Issue by amgadfahmi** [webglearth/webglearth2#77]
MapQuest have changed there API to use keys based on the plan the developer chooses, all the maps now are not showing probably and you can see it at http://examples.webglearth.com/#satellite 

Any changes are going from your side guys now ! how can I use my MapQuest key with your component !

**Comment by petrsloup** [comment]
The examples no longer use MapQuest tiles.

There are currently no plans to support the key-based MapQuest tiles, but pull requests are always welcome.
