### ISSUE TITLE
Instructions on how to create a non-minified version of webglearth

### ISSUE THREAD

**Issue by philipjmurphy** [webglearth/webglearth2#78]
Can you post a few instructions on how to create a non-minified version of webglearth2. I can build a production version, but not a debug version. Thanks

**Comment by klokan** [comment]
Thanks @philipjmurphy for your feedback!

Could you please write the exact questions you have - so we know what is not clear now to new developers who are getting familiar with this open-source project?

Readme.md at https://github.com/webglearth/webglearth2/ describes the basics of usage.

Debug mode runs via "make serve", which serves the debug version of API on localhost, automatically recompiled on every reload of src/api-l.html and other examples - see https://github.com/webglearth/webglearth2/search?utf8=%E2%9C%93&q=api-debug

For advanced info check the content of "Makefile" and get familiar with the tools used there.

**Comment by philipjmurphy** [comment]
Thanks. I've got debug mode working now. However, for beginners it would help to know exactly what needs to be included in your HTML once you have the plovr server running. 

To set this up I needed to run the following commands:

```
cd ~
git clone https://github.com/webglearth/webglearth2.git
cd webglearth2
git submodule update --init
make cesium
make plovr
make serve
```

In the following example I have Cesium.js being served from a http server running at ~/webglearth2 (Node's http-server is handy for this) and the plovr server is serving the other code.

```
<script src="http://192.168.1.18:8080/cesium/Build/Cesium/Cesium.js"></script>
<script src="http://192.168.1.18:9810/compile?id=api-debug"></script>
```
I can see that the ?id=api-debug maps to id name in the api-debug.json file. 

I've also been able to run the src-app (this is the app that is running at http://www.webglearth.com/). It wasn't initially clear to me the difference between the api and app json files (obvious now).

To run the source app I needed to visit: 

`http://192.168.1.18:8080/src-app/main.html`

Note that the webfont webglearth.woff/ttf is not committed, so I just downloaded the woff one from original site and placed it in ~/webglearth2/deploy/fonts and src-app is working too.

Finally, if I wanted to change the Closure compiler to RAW but there is a bug (https://groups.google.com/d/msg/plovr/ChZO4JxTTAE/rljmTZWGKX0J) in plover that makes it serve the content from the referer instead of the host. To get around this I ran a proxy server on my local machine (http-server -p 9810 -P http://192.168.1.18:9810) to direct the incorrect requests to the correct server). 

Debugging in Chrome this is working very well. CTRL+SHIFT+F in dev tools to find api code, insert breakpoint and you are good to go.

**Comment by klokan** [comment]
Thanks @philipjmurphy for this summary - we can point people to your comment.

Do you think it would make sense to add it to README.md?

What about the API vs APP difference - how would you describe it to a newbie?
