### ISSUE TITLE
Is there a proper way to dispose of webglearth2 ?

### ISSUE THREAD

**Issue by bugdanov** [webglearth/webglearth2#80]
Hello ! Webglearth2 is great but I have a problem.

Unreferencing the WE.map object and removing the DOM container does not seems enough to dispose of webglearth2 instance and related workers  or event handlers

I have something like this:
```
<div ng-if="earth_visible">
   <div id="earth_div"></div>
</div>
```
```
$scope.earth_visible=true;
$scope.earth=new WE.map('earth_div', options);
```

When I leave the view I try to dispose of webglearth2 with:

```
$scope.earth=null;
$scope.earth_visible=false;
```

However when I run the javascript profiler I see that api.js is still active (requestAnimationFrame, ... )
And the instances are cumulating when entering and leaving the view.

Is there a proper way to dispose of webglearth2 (without using an iframe) ?

**Comment by luxigo** [comment]
:+1: 

Cesium.Viewer.destroy() must be called in order to properly dispose of the Cesium Viewer instance including event handlers and concurrent processes (eg: requestAnimationFrame())

A WE.map.destroy() method needs to be implemented.

**Comment by luxigo** [comment]
$scope.earth.getCesiumScene().destroy() is your friend here and seems to solve this issue.

**Comment by bugdanov** [comment]
Thanks bro ! :-P
