### ISSUE TITLE
panTo Duration Issues

### ISSUE THREAD

**Issue by JamesIves** [webglearth/webglearth2#83]
Having issues with the duration when using `panTo`

Am I calling this correctly? It pans but the duration is always default no matter what value I set it to. 

`map.panTo([64.710824, -22.148438], {duration: 100});`

**Comment by jdakowicz** [comment]
I found the issue in source code, there is a bug [here](https://github.com/webglearth/webglearth2/blob/master/src/api-l.js#L106).
This method is taking 7 parameters but we are passing 8 and the 8th one is our duration.
Quick fix is to override the panTo method in your script after you import the lib i.e.:
`WebGLEarth.prototype.panTo = function(center, opt_opts) {
          if (!center.length) center = [center['lat'], center['lng']];
          opt_opts = opt_opts || {};
          this.flyTo(center[0], center[1], undefined, undefined, 0, 0, opt_opts['duration'])
        };`
Or do a fix inside the imported file, find that method and change into this: `r("WebGLEarth.prototype.panTo",function(a,b){x(a)||(a=[a.lat,a.lng]);b=b||{};this.Fa(a[0],a[1],void 0,void 0,0,0,b.duration)});`

**Comment by klokan** [comment]
Great you tracked it down to code @jdakowicz 

Could you please make a pull request here on GitHub - with the fix?

**Comment by liuweiGL** [comment]
JamesIves is great. By the way, I'd like to remind people that the unit is ` seconds `

**Comment by syneva-runyan** [comment]
Created a PR with JamesIve's fix described above https://github.com/webglearth/webglearth2/pull/109

**Comment by williamdarkocode** [comment]
So whats the solution to this then? I'm getting sick of poorly designed apis.

**Comment by JamesIves** [comment]
This issue is almost 4 years old, and the project is unmaintained according to the README. There's no reason to be rude however.
