### ISSUE TITLE
how to use cesium api

### ISSUE THREAD

**Issue by hon** [webglearth/webglearth2#84]
Hi,
Is there a way to use cesium api in ‘WE‘ object? And if yes, is that to say everything cesium can do webglearth can do, too?
Thanks.

**Comment by petrsloup** [comment]
You can use `WE.getCesiumScene()` to get the underlying Cesium object and use it as you wish.

**Comment by hon** [comment]
It throws "test.html:9 Uncaught TypeError: WE.getCesiumScene is not a function".

**Comment by hon** [comment]
getCesiumScene is instanance method not static.
